
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: bash
  category: shells
  version: ">=0"

package_dir: /sh
prelude:
- mkdir -p /sh/bin
steps:
- cd /sh/bin && ln -s bash sh
