
requires:
- name: musl-toolchain
  category: system
  version: "0.9.9"
- name: make
  category: development
  version: ">=0"
- name: perl
  category: lang
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- CC="gcc -static"
- PACKAGE_NAME=busybox

package_dir: /busybox
prelude:
- |
   wget https://busybox.net/downloads/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.bz2 && \
   tar -xvjf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.bz2 && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && make defconfig && make CONFIG_PREFIX=/${PACKAGE_NAME}

steps:
- cd ${PACKAGE_NAME} && make CONFIG_PREFIX=/${PACKAGE_NAME} install
