requires:
- name: musl-toolchain
  category: system
  version: ">=0"
  
env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64

unpack: true

includes:
- ^/lib$
- ^/lib/ld-musl-.*.so.1
- ^/lib/libc.so$
