
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"

- name: perl
  category: lang
  version: ">=0"
env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64


package_dir: /libcap
prelude:
- |
  wget https://kernel.org/pub/linux/libs/security/linux-privs/${PACKAGE_NAME}/libcap-${PACKAGE_VERSION}.tar.xz && \ 
   tar -xvf libcap-${PACKAGE_VERSION}.tar.xz && mv libcap-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && make lib=lib prefix=/usr

steps:
- | 
   cd ${PACKAGE_NAME} && make lib=lib prefix=/usr install && make DESTDIR=/libcap lib=lib prefix=/usr install
  
