
requires:
- name: musl-toolchain
  category: system
  version: "0.9.9"
- name: perl
  category: lang
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64


package_dir: /automake
prelude:
- |
   wget http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && ./configure --prefix=/usr && make

steps:
- | 
   cd ${PACKAGE_NAME} && make DESTDIR=/automake install && \
   cp -rfv /${PACKAGE_NAME}/* /
  
