
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: python
  category: lang
  version: ">=0"

env:
- CFLAGS=-Wno-error

package_dir: /meson
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   git clone https://github.com/mesonbuild/meson ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && git checkout -b build ${PACKAGE_VERSION} && mkdir -p /${PACKAGE_NAME} && \
   python setup.py install \
        --root /${PACKAGE_NAME} \
        --single-version-externally-managed \
        --verbose && \
   cp -rfv /${PACKAGE_NAME}/* /
