image: "alpine"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64

prelude:
- |
  apk update && \
  apk add git build-base && \
  git clone https://github.com/richfelker/musl-cross-make && \
  cd musl-cross-make  && \
  git checkout v${PACKAGE_VERSION} -b build && \
  cp -rfv ../config.mak ./ && \
  rm -rfv patches/linux-headers-4.19.88/* && \
    mkdir -p /musl/usr/ && \
  make TARGET=$MUSL_TARGET OUTPUT=/musl -j 8

package_dir: "/musl"

steps:
- |
   cd musl-cross-make && \
   make TARGET=$MUSL_TARGET OUTPUT=/musl install -j 8 

