image: "alpine"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- TARGET=$MUSL_TARGET

prelude:
- |
  apk update && \
  apk add git build-base make && \
  git clone https://github.com/richfelker/musl-cross-make && \
  cd musl-cross-make  && \
  git checkout v${PACKAGE_VERSION} -b build && \
  cp -rfv ../config.mak ./ && \
  rm -rfv patches/linux-headers-4.19.88/* && \
    mkdir -p /musl/
package_dir: "/musl"

steps:
- |
  set -x && \
   cd musl-cross-make && \
   patch -Np1 -i ../patches/sysroot.patch && \
   mkdir -p output/bin && \
   make -j 8 && \
   make install && \
   ls -liah output && \
   PATH=$PATH:$PWD/output/bin:$PWD/output/$TARGET/bin make NATIVE=1 -j8 && \
   PATH=$PATH:$PWD/output/bin:$PWD/output/$TARGET/bin make NATIVE=1 install && \
   apk del build-base && \ 
   cp -rfv /musl/* / 

