
requires:
- name: musl-toolchain
  category: system
  version: "0.9.9"
- name: make
  category: development
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- FORCE_UNSAFE_CONFIGURE=1
- PACKAGE_NAME=gettext

package_dir: /libtextstyle
prelude:
- |
   wget http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.xz && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.xz && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   rm -rf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.xz && \
   cd ${PACKAGE_NAME}/libtextstyle && mkdir -p /libtextstyle && gt_cv_func_printf_posix=yes \
   ./configure --prefix=/usr && \
   make DESTDIR=/libtextstyle

steps:
- cd ${PACKAGE_NAME}/libtextstyle && make DESTDIR=/libtextstyle install && make install && cd ../../ && rm -rf ${PACKAGE_NAME} 
