
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: perl
  category: lang
  version: ">=0"
- name: autoconf
  category: utils
  version: ">=0"
- name: automake
  category: development
  version: ">=0"
- name: libtool
  category: development
  version: ">=0"

env:
- CFLAGS="-fPIC"

package_dir: /libressl
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   git config --global advice.detachedHead false && \
   git clone https://github.com/libressl-portable/portable ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && git checkout -b build v${PACKAGE_VERSION} && mkdir -p /${PACKAGE_NAME} && \
   echo libressl-v${PACKAGE_VERSION} > OPENBSD_BRANCH && \
   sed -i 's/git pull --rebase//g' update.sh && \
   ./autogen.sh && ./configure --prefix=/usr   && \
   make -j8 && \
   make DESTDIR=/${PACKAGE_NAME} install && \
   cp -rfv /${PACKAGE_NAME}/* /
