
requires:
- name: musl-toolchain
  category: system
  version: "0.9.9"
  
env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64


package_dir: /musl-utils
prelude:
- |
   gcc -static getconf.c -o getconf && \
   gcc -static getent.c -o getent && \
   gcc -static iconv.c -o iconv

steps:
- | 
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   mkdir -p /${PACKAGE_NAME}/sbin && \
   install -D getent getconf iconv /$PACKAGE_NAME/usr/bin && \
   install -D -m755 ldconfig "/$PACKAGE_NAME"/sbin && \
   cp -rfv /${PACKAGE_NAME}/* /
  
