name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
    # https://github.community/t/worker-running-out-of-disk-space/18245
    - name: Patch Docker Daemon data-root
      run: |
        DOCKER_DATA_ROOT='/mnt/var/lib/docker'
        DOCKER_DAEMON_JSON='/etc/docker/daemon.json'
        sudo mkdir -p "${DOCKER_DATA_ROOT}"
        jq --arg dataroot "${DOCKER_DATA_ROOT}" '. + {"data-root": $dataroot}' "${DOCKER_DAEMON_JSON}" > "/tmp/docker.json.tmp"
        sudo mv "/tmp/docker.json.tmp" "${DOCKER_DAEMON_JSON}"
        sudo systemctl restart docker
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.3' # The Go version to download (if necessary) and use.
    - name: Login to DockerHub Registry
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo ${{ secrets.DOCKERIO_PASSWORD }} | docker login -u ${{ secrets.DOCKERIO_USERNAME }} --password-stdin
    - name: Set Push options
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo ::set-env name=BUILD_ARGS::--pull --push --image-repository mocaccinoos/micro-cache
    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      env:
        PREVIOUS: ${{ github.event.before }}
      run: |
        make deps
        git clone https://github.com/mudler/luet.git
        cd luet
        git checkout develop
        make build && sudo cp -rfv luet /usr/bin/luet
        cd ..
        rm -rf luet
        curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff
        make build-all create-repo
    - name: Deploy 🚀
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        curl https://gist.githubusercontent.com/mudler/4fc89a4318e9987509727d4f5b47f546/raw/49e3cb612f8e9885082526744e2d8444320861c5/keybase.sh > keybase.sh

        docker run --rm \
        -e KEYBASE_DEVICENAME=$KEYBASE_DEVICENAME -e KEYBASE_USERNAME="$KEYBASE_USERNAME" \
        -e KEYBASE_PAPERKEY="$KEYBASE_PAPERKEY" \
        -e KEYBASE_SERVICE=1 -v $PWD:/data -v $PWD/keybase.sh:/keybase.sh \
        keybaseio/client:stable \
        bash /keybase.sh fs rm -r '/keybase/public/mocaccino/micro/*' || true

        docker run --rm \
        -e KEYBASE_DEVICENAME=$KEYBASE_DEVICENAME -e KEYBASE_USERNAME="$KEYBASE_USERNAME" \
        -e KEYBASE_PAPERKEY="$KEYBASE_PAPERKEY" \
        -e KEYBASE_SERVICE=1 -v $PWD/build:/data -v $PWD/keybase.sh:/keybase.sh \
        keybaseio/client:stable \
        bash /keybase.sh fs cp -r -f '/data/*' /keybase/public/mocaccino/micro
      env:
        KEYBASE_DEVICENAME: ${{ secrets.KEYBASE_DEVICENAME }}
        KEYBASE_PAPERKEY: ${{ secrets.KEYBASE_PAPERKEY }}
        KEYBASE_USERNAME: ${{ secrets.KEYBASE_USERNAME }}
